chore: acceptance tests should run as part of hotfix build

diff --git a/.github/workflows/publish-hotfix.yml b/.github/workflows/publish-hotfix.yml
--- a/.github/workflows/publish-hotfix.yml
+++ b/.github/workflows/publish-hotfix.yml
@@ -34,6 +34,31 @@ jobs:
           npm run lint
           npm test
 
+      - name: Acceptance & environment emulation tests
+        # the script is basically `npm run test:acceptance:docker && npm run test:acceptance:proxy`
+        # but with some extra logging and error handling to help debug failures
+        run: |
+          set +e
+          docker compose -f compose.yml -f test/acceptance/compose.yml \
+            run --rm --build --pull always --quiet-pull test
+          if [ $? -ne 0 ]; then
+            echo -e '\n\n====> Dumping DAL logs...\n'
+            docker logs fcp-dal-api-fcp-dal-api-1 | jq
+            docker compose down --remove-orphans
+            exit 1
+          fi
+          docker compose -f compose.yml -f test/acceptance/compose.yml -f test/acceptance/cdp-mock-check.yml \
+            run --rm --quiet-pull test # no need to build or pull again
+          if [ $? -ne 0 ]; then
+            echo -e '\n\n====> Dumping DAL logs...\n'
+            docker logs fcp-dal-api-fcp-dal-api-1 | jq
+            docker compose down --remove-orphans
+            exit 1
+          fi
+          docker compose down --remove-orphans
+        # TODO: re-enable mTLS tests when startup health check issue is resolved
+        #  && npm run test:acceptance:proxy:mtls
+
       - name: Publish Hot Fix
         uses: DEFRA/cdp-build-action/build-hotfix@f13fc42004f99a1df2e21ce1ff488cc72c897e40 # 17 Jul 2026
         with:
